"""Constants for the Soniox STT integration."""

from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

DOMAIN = "soniox_stt"
TITLE = "Soniox Speech-to-Text"
DEFAULT_MODEL = "stt-async-v4"
AUTO_LANGUAGE = "auto"
TRANSCRIPTION_TIMEOUT_SECONDS = 60
POLL_INTERVAL_SECONDS = 1.0

LANGUAGE_NAMES: dict[str, str] = {
    "ar": "Arabic",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "ca": "Catalan",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Persian",
    "fi": "Finnish",
    "fr": "French",
    "ga": "Irish",
    "gl": "Galician",
    "gu": "Gujarati",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "hy": "Armenian",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "kk": "Kazakh",
    "kn": "Kannada",
    "ko": "Korean",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mi": "Maori",
    "mk": "Macedonian",
    "mr": "Marathi",
    "ms": "Malay",
    "ne": "Nepali",
    "nl": "Dutch",
    "no": "Norwegian",
    "pa": "Punjabi",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sr": "Serbian",
    "sv": "Swedish",
    "sw": "Swahili",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "tl": "Tagalog",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "vi": "Vietnamese",
    "zh": "Chinese",
}

LANGUAGE_TAGS: dict[str, tuple[str, ...]] = {
    "ar": ("ar", "ar-SA"),
    "be": ("be", "be-BY"),
    "bg": ("bg", "bg-BG"),
    "bn": ("bn", "bn-BD"),
    "ca": ("ca", "ca-ES"),
    "cs": ("cs", "cs-CZ"),
    "cy": ("cy", "cy-GB"),
    "da": ("da", "da-DK"),
    "de": ("de", "de-DE"),
    "el": ("el", "el-GR"),
    "en": ("en", "en-US", "en-GB", "en-AU"),
    "es": ("es", "es-ES", "es-MX"),
    "et": ("et", "et-EE"),
    "eu": ("eu", "eu-ES"),
    "fa": ("fa", "fa-IR"),
    "fi": ("fi", "fi-FI"),
    "fr": ("fr", "fr-FR", "fr-CA"),
    "ga": ("ga", "ga-IE"),
    "gl": ("gl", "gl-ES"),
    "gu": ("gu", "gu-IN"),
    "he": ("he", "he-IL"),
    "hi": ("hi", "hi-IN"),
    "hr": ("hr", "hr-HR"),
    "hu": ("hu", "hu-HU"),
    "hy": ("hy", "hy-AM"),
    "id": ("id", "id-ID"),
    "it": ("it", "it-IT"),
    "ja": ("ja", "ja-JP"),
    "kk": ("kk", "kk-KZ"),
    "kn": ("kn", "kn-IN"),
    "ko": ("ko", "ko-KR"),
    "lt": ("lt", "lt-LT"),
    "lv": ("lv", "lv-LV"),
    "mi": ("mi", "mi-NZ"),
    "mk": ("mk", "mk-MK"),
    "mr": ("mr", "mr-IN"),
    "ms": ("ms", "ms-MY"),
    "ne": ("ne", "ne-NP"),
    "nl": ("nl", "nl-NL", "nl-BE"),
    "no": ("no", "nb-NO", "nn-NO"),
    "pa": ("pa", "pa-IN"),
    "pl": ("pl", "pl-PL"),
    "pt": ("pt", "pt-PT", "pt-BR"),
    "ro": ("ro", "ro-RO"),
    "ru": ("ru", "ru-RU"),
    "sk": ("sk", "sk-SK"),
    "sl": ("sl", "sl-SI"),
    "sr": ("sr", "sr-RS"),
    "sv": ("sv", "sv-SE"),
    "sw": ("sw", "sw-KE"),
    "ta": ("ta", "ta-IN"),
    "te": ("te", "te-IN"),
    "th": ("th", "th-TH"),
    "tl": ("tl", "tl-PH", "fil-PH"),
    "tr": ("tr", "tr-TR"),
    "uk": ("uk", "uk-UA"),
    "ur": ("ur", "ur-PK"),
    "vi": ("vi", "vi-VN"),
    "zh": ("zh", "zh-CN", "zh-TW"),
}
